trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables: 
  GCC_LOCKED:   gcc@7
  BASE_LOCKED:  ubuntu

# Images to build
strategy:
  matrix:
    openmpi3:
      BASE_IMAGE: 19.09-$(BASE_LOCKED)
      MPI_SPEC:   openmpi@3.0.2%$(GCC_LOCKED) openmpi@3.1.3%$(GCC_LOCKED)
      TAG:        openmpi3
    mpich3:
      BASE_IMAGE: 19.09-$(BASE_LOCKED)
      MPI_SPEC:   mpich@3.0.4%$(GCC_LOCKED) mpich@3.1.4%$(GCC_LOCKED) mpich@3.2.1%$(GCC_LOCKED)
      TAG:        mpich3
    mvapich2:
      BASE_IMAGE: 19.09-$(BASE_LOCKED)
      MPI_SPEC:   mvapich2@2.1%$(GCC_LOCKED) fabrics=mrail mvapich2@2.2%$(GCC_LOCKED) fabrics=mrail mvapich2@2.3%$(GCC_LOCKED) fabrics=mrail
      TAG:        mvapich2

# Steps to build images
steps:
- script: |
    printf "##vso[task.setvariable variable=DATE_TAG;]%s\n" $(date "+%g.%m")
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHub
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    repository: liambindle/build-matrix-images-base-mpi
    tags: $(DATE_TAG)-$(TAG)
    arguments: |
      --build-arg BASE_IMAGE="liambindle/build-matrix-images-base:$(BASE_IMAGE)"
      --build-arg MPI_SPEC="$(MPI_SPEC)"
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: DockerHub
    repository: liambindle/build-matrix-images-base-mpi
    command: push
    tags: |
      $(DATE_TAG)-$(TAG)